micronaut:
  application:
    name: pixKeymanagerGrpc

datasources:
  default:
    url: jdbc:mysql://localhost:3306/db_pix_grpc?createDatabaseIfNotExist=true
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: senhamysql2
    schema-generate: CREATE_DROP
    dialect: MYSQL
jpa.default.properties.hibernate.hbm2ddl.auto: update
